apiVersion: v1
kind: Service
metadata:
  name: ebookmgmt-dashboard
  labels:
    app: ebookmgmt-dashboard
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ebookmgmt-dashboard